services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri ./mlruns
      --default-artifact-root ./mlruns

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana-oss:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   depends_on:
  #     - prometheus

  # Layanan keempat: MLflow Model Serving
  mlflow-serving:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "8001:8001"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow models serve
      --tracking-uri http://mlflow:5000
      --model-uri "models:/prediksi-penyakit-jantung/2"
      --host 0.0.0.0
      --port 8001
      --enable-mlserver
    depends_on:
      - mlflow
