# 225150207111001_1 MUHAMMAD NADHIF_1
# 225150201111002_2 NALENDRA MARCHELO_2
# 225150200111005_3 NARENDRA ATHA ABHINAYA_3
# 225150200111003_4 YOSUA SAMUEL EDLYN SINAGA_4

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860" # Port untuk Gradio UI
      - "8000:8000" # Port untuk metrik Prometheus
    environment:
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
      - MLFLOW_TRACKING_URI=https://dagshub.com/<user>/<repo>.mlflow
    networks:
      - mlops-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - app
    networks:
      - mlops-net

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mlops-net

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  mlops-net:
    driver: bridge
