services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860" # Port untuk Gradio UI
      - "8000:8000" # Port untuk metrik Prometheus
    environment:
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
    networks:
      - mlops-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - mlops-net

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - mlops-net

networks:
  mlops-net:
    driver: bridge
