# 225150207111001_1 MUHAMMAD NADHIF_1
# 225150201111002_2 NALENDRA MARCHELO_2
# 225150200111005_3 NARENDRA ATHA ABHINAYA_3
# 225150200111003_4 YOSUA SAMUEL EDLYN SINAGA_4

# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "heart_disease_app"
    static_configs:
      - targets: ["app:8000"]

remote_write:
  - url: https://prometheus-prod-52-prod-ap-southeast-2.grafana.net/api/prom/push
    basic_auth:
      username: 2564023
      password: glc_eyJvIjoiMTQ4NTM0NCIsIm4iOiJzdGFjay0xMzE5ODk0LWhtLXdyaXRlLW1sb3BzdGVzdDEiLCJrIjoiM0x5Qzl0MmY0NWZrcjBmdzZYSG85MFY3IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMiJ9fQ==
