# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "heart_disease_app"
    # DIUBAH: Target sekarang adalah layanan 'app' di port 8000, tempat Flask berjalan
    static_configs:
      - targets: ["app:8000"]

# Bagian ini untuk koneksi ke Grafana Cloud, bisa dibiarkan jika Anda menggunakannya
remote_write:
  - url: https://prometheus-prod-52-prod-ap-southeast-2.grafana.net/api/prom/push
    basic_auth:
      username: 2564023
      password: glc_eyJvIjoiMTQ4NTM0NCIsIm4iOiJzdGFjay0xMzE5ODk0LWhtLXdyaXRlLW1sb3BzdGVzdDEiLCJrIjoiM0x5Qzl0MmY0NWZrcjBmdzZYSG85MFY3IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMiJ9fQ==
