# 225150207111001_1 MUHAMMAD NADHIF_1
# 225150201111002_2 NALENDRA MARCHELO_2
# 225150200111005_3 NARENDRA ATHA ABHINAYA_3
# 225150200111003_4 YOSUA SAMUEL EDLYN SINAGA_4

name: Continuous Deployment

# Pemicu
on:
  push:
    branches:
      - main

jobs:
  deploy-to-hugging-face:
    name: Deploy to Hugging Face Space
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "hf@actions"
          git config --global user.name "Hugging Face Actions Bot"
          git remote add space https://NalendraMarchelo:${HF_TOKEN}@huggingface.co/spaces/NalendraMarchelo/Heart-Disease-Prediction
          git push --force space main
