name: Continuous Integration

# Pemicu
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-docker-image:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t heart-disease-app:test .
