# .github/workflows/retraining_pipeline.yml
name: Automated Retraining with Dynamic Data

on:
  repository_dispatch:
    types: [trigger-retraining]

jobs:
  retrain-and-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Update Training Dataset
        run: python update_dataset.py

      - name: Commit and Push Updated Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [ -f "data/new_logs.csv" ]; then
            git add data/combined_data.csv data/new_logs.csv
            git commit -m "feat: Append new prediction logs to training data"
            git push
          else
            echo "No new log file to commit."
          fi

      - name: Run Training Script
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python train.py --dataset data/combined_data.csv --run_name "Automated Retraining"

      - name: Promote New Model to Production
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python promote_model.py

      - name: Trigger Model Reload in Application
        run: |
          # Perintah curl ini akan "mengetuk" endpoint /reload di layanan 'app' Anda
          # Perlu waktu beberapa detik agar layanan siap setelah docker-compose up
          echo "Menunggu aplikasi siap..."
          sleep 15 
          curl -X POST http://app:8000/reload
