name: Automated Model Retraining

on:
  repository_dispatch:
    types: [trigger-retraining]

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Training Script
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python train.py --dataset data/combined_data.csv --run_name "Automated Retraining via GitHub Actions"

      - name: Promote Model to Production
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python promote_model.py
