# .github/workflows/retraining_pipeline.yml
name: Automated Retraining with Dynamic Data

on:
  repository_dispatch:
    types: [trigger-retraining]

jobs:
  retrain-and-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Update Training Dataset
        run: python update_dataset.py

      - name: Commit and Push Updated Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [ -f "data/new_logs.csv" ]; then
            git add data/combined_data.csv data/new_logs.csv
            git commit -m "feat: Append new prediction logs to training data"
            git push
          else
            echo "No new log file to commit."
          fi

      - name: Run Training Script
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python train.py --dataset data/combined_data.csv --run_name "Automated Retraining"

      - name: Promote New Model to Production
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python promote_model.py

      - name: Trigger Deployment
        env:
          RELOAD_SECRET: ${{ secrets.RELOAD_SECRET_TOKEN }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token YOUR_GITHUB_TOKEN" \
          https://api.github.com/repos/NalendraMarchelo/HeartDiseasesDetection/dispatches \
               -d '{"event_type": "trigger-retraining", "client_payload": {"message": "New data available for retraining"}}'
