# .github/workflows/retraining_pipeline.yml

name: Automated Model Retraining and Data Versioning

on:
  repository_dispatch:
    types: [trigger-retraining]

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Combine Datasets for Retraining
        run: python combine_data.py

      - name: Run Training Script
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python train.py --dataset data/combined_data.csv --run_name "Automated Retraining via GitHub Actions"

      - name: Promote New Model to Production
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python promote_model.py

      - name: Version and Push New Data to DagsHub
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Konfigurasi Git di dalam runner
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Tambahkan data baru ke DVC
          dvc add data/combined_data.csv

          # Commit file .dvc yang baru
          git add data/combined_data.csv.dvc
          git commit -m "feat: Update combined training data after automated retraining"

          # Push data ke DagsHub DVC remote
          dvc push

          # Push perubahan file .dvc ke Git
          git push
